// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO6M_iCvVjhw5IfwmM2I2W4oZucQvgK5s',
    appId: '1:849236471189:web:5c0b95ed2806c488c05a9c',
    messagingSenderId: '849236471189',
    projectId: 'disaster-shiled-73810',
    authDomain: 'disaster-shiled-73810.firebaseapp.com',
    storageBucket: 'disaster-shiled-73810.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4gmyShoviYGCode8h0hHu4BB7UycrYHM',
    appId: '1:849236471189:android:ef1b41dcabbcb9d7c05a9c',
    messagingSenderId: '849236471189',
    projectId: 'disaster-shiled-73810',
    storageBucket: 'disaster-shiled-73810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdRsoREzNhZNsXmF96bjihEAv1r3X1Crg',
    appId: '1:849236471189:ios:daa88f71ed3203aec05a9c',
    messagingSenderId: '849236471189',
    projectId: 'disaster-shiled-73810',
    storageBucket: 'disaster-shiled-73810.firebasestorage.app',
    iosBundleId: 'com.example.diasasterShield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdRsoREzNhZNsXmF96bjihEAv1r3X1Crg',
    appId: '1:849236471189:ios:daa88f71ed3203aec05a9c',
    messagingSenderId: '849236471189',
    projectId: 'disaster-shiled-73810',
    storageBucket: 'disaster-shiled-73810.firebasestorage.app',
    iosBundleId: 'com.example.diasasterShield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO6M_iCvVjhw5IfwmM2I2W4oZucQvgK5s',
    appId: '1:849236471189:web:4c3bc846ed636c89c05a9c',
    messagingSenderId: '849236471189',
    projectId: 'disaster-shiled-73810',
    authDomain: 'disaster-shiled-73810.firebaseapp.com',
    storageBucket: 'disaster-shiled-73810.firebasestorage.app',
  );
}
