"""add zone_id to alert_responses

Revision ID: 1e3ecb874c12
Revises: 5dd50609dfbe
Create Date: 2026-01-18 23:31:10.573150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3ecb874c12'
down_revision = '5dd50609dfbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_responses', schema=None) as batch_op:
        batch_op.drop_column('alert_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
