"""update alert_responses to use zone_id

Revision ID: 5dd50609dfbe
Revises: 7f84049ae3bf
Create Date: 2026-01-18 22:57:10.205023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd50609dfbe'
down_revision = '7f84049ae3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('alert_responses_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'zones', ['zone_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('alert_responses_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('zone_id')

    # ### end Alembic commands ###
